export interface LeadEmailData {
  companyName: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  sqft: number;
  pitch: string;
  material: string;
  estimateLow: number;
  estimateHigh: number;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const currencyFmt = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 0,
});

export function buildLeadEmailHtml(data: LeadEmailData): string {
  const firstName = escapeHtml(data.firstName);
  const lastName = escapeHtml(data.lastName);
  const email = escapeHtml(data.email);
  const phone = escapeHtml(data.phone);
  const companyName = escapeHtml(data.companyName);
  const pitch = escapeHtml(data.pitch);
  const material = escapeHtml(data.material);
  const sqft = data.sqft;
  const low = currencyFmt.format(data.estimateLow);
  const high = currencyFmt.format(data.estimateHigh);

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8" /></head>
<body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
  <div style="background: #2563eb; color: #fff; padding: 20px; text-align: center;">
    <h1 style="margin: 0; font-size: 22px;">New Roofing Lead</h1>
  </div>

  <div style="padding: 24px;">
    <h2 style="margin-top: 0; font-size: 18px; color: #1e40af;">Contact Information</h2>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; font-weight: bold; width: 120px;">Name</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${firstName} ${lastName}</td>
      </tr>
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; font-weight: bold;">Email</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;"><a href="mailto:${email}">${email}</a></td>
      </tr>
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; font-weight: bold;">Phone</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;"><a href="tel:${phone}">${phone}</a></td>
      </tr>
    </table>

    <h2 style="font-size: 18px; color: #1e40af;">Roof Details</h2>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; font-weight: bold; width: 120px;">Square Feet</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${sqft}</td>
      </tr>
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; font-weight: bold;">Pitch</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${pitch}</td>
      </tr>
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; font-weight: bold;">Material</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${material}</td>
      </tr>
    </table>

    <div style="background: #eff6ff; border: 2px solid #2563eb; border-radius: 8px; padding: 20px; text-align: center; margin-bottom: 20px;">
      <div style="font-size: 14px; color: #64748b; margin-bottom: 8px;">Estimated Range</div>
      <div style="font-size: 28px; font-weight: bold; color: #2563eb;">${low} &ndash; ${high}</div>
    </div>

    <p style="font-size: 12px; color: #94a3b8; text-align: center;">
      This lead was generated by the ${companyName} roofing estimate widget.
    </p>
  </div>
</body>
</html>`;
}
